spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${DB.host}:${DB.port:3306}/${DB.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: ${DB.username}
    password: ${DB.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为资源文件建立映射
  web:
    resources:
      add-mappings: false

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t %r %s %b'
      prefix: access_log
      rotate: true
      suffix: .log
